# Minimal Clanker Configuration
# Copy this to ~/.clanker.yaml and fill in the placeholders.

ai:
  # Pick a provider and make sure its credentials exist.
  # If you omit this, clanker falls back to openai.
  default_provider: gemini-api

  providers:
    gemini-api:
      model: gemini-3-pro-preview
      api_key_env: GEMINI_API_KEY

    # OpenAI example:
    # Note: this CLI currently reads `ai.providers.openai.api_key` (not `api_key_env`).
    # You can either paste your key here or pass it at runtime with:
    #   clanker ask --ai-profile openai --openai-key "$OPENAI_API_KEY" "..."
    openai:
      model: gpt-5
      api_key: ""

infra:
  default_provider: aws
  default_environment: dev

  aws:
    environments:
      dev:
        profile: your-aws-profile
        region: us-east-1


# -------------------- Optional blocks --------------------

# Use Bedrock (Claude) instead of Gemini API:
# ai:
#   default_provider: bedrock
#   providers:
#     bedrock:
#       aws_profile: your-bedrock-aws-profile
#       region: us-east-1
#       model: us.anthropic.claude-sonnet-4-20250514-v1:0

# Use OpenAI:
# ai:
#   default_provider: openai
#   providers:
#     openai:
#       model: gpt-5
#       api_key: "sk-..."  # or pass at runtime: clanker ask --openai-key "$OPENAI_API_KEY" ...

# Multiple AWS environments (dev/stage/prod):
# infra:
#   default_provider: aws
#   default_environment: dev
#   aws:
#     environments:
#       dev:   { profile: your-dev-profile,   region: us-east-1 }
#       stage: { profile: your-stage-profile, region: us-east-1 }
#       prod:  { profile: your-prod-profile,  region: us-east-1 }

# GitHub context for `clanker ask --github ...`:
# github:
#   token: "ghp_..."   # optional for public repos
#   owner: your-org
#   repo: your-repo

# AWS service keywords (used by internal routing). Note: this is under `aws.*`:
# aws:
#   service_keywords:
#     api: [api, gateway]
#     serverless: [lambda, step-functions]

# Postgres (for `clanker postgres ...`):
# postgres:
#   default_connection: dev
#   connections:
#     dev:
#       host: localhost
#       port: 5432
#       database: your_db
#       username: postgres

# Terraform (for `clanker terraform ...` and `clanker ask --terraform ...`):
# terraform:
#   default_workspace: dev
#   workspaces:
#     dev:
#       path: /path/to/infra

# General settings:
# verbose: false
# timeout: 30
