# Minimal Clanker Configuration
# Copy this to ~/.clanker.yaml and fill in the placeholders.

ai:
  # Pick a provider and make sure its credentials exist.
  # If you omit this, clanker falls back to openai.
  default_provider: gemini-api

  providers:
    gemini-api:
      model: gemini-2.5-flash
      api_key_env: GEMINI_API_KEY

    # OpenAI example:
    # Note: this CLI currently reads `ai.providers.openai.api_key` (not `api_key_env`).
    # You can either paste your key here or pass it at runtime with:
    #   clanker ask --ai-profile openai --openai-key "$OPENAI_API_KEY" "..."
    openai:
      model: gpt-5
      api_key: ""

    # DeepSeek example:
    # deepseek:
    #   model: deepseek-chat
    #   api_key_env: DEEPSEEK_API_KEY

    # MiniMax example:
    # minimax:
    #   model: MiniMax-M2.5
    #   api_key_env: MINIMAX_API_KEY

infra:
  default_provider: aws
  default_environment: dev

  aws:
    environments:
      dev:
        profile: your-aws-profile
        region: us-east-1

  gcp:
    project_id: your-gcp-project-id


# -------------------- Optional blocks --------------------

# Use Bedrock (Claude) instead of Gemini API:
# ai:
#   default_provider: bedrock
#   providers:
#     bedrock:
#       aws_profile: your-bedrock-aws-profile
#       region: us-east-1
#       model: us.anthropic.claude-sonnet-4-20250514-v1:0

# Use OpenAI:
# ai:
#   default_provider: openai
#   providers:
#     openai:
#       model: gpt-5
#       api_key: "sk-..."  # or pass at runtime: clanker ask --openai-key "$OPENAI_API_KEY" ...

# Use DeepSeek:
# ai:
#   default_provider: deepseek
#   providers:
#     deepseek:
#       model: deepseek-chat  # or deepseek-reasoner
#       api_key_env: DEEPSEEK_API_KEY
#   # Pass at runtime: clanker ask --ai-profile deepseek --deepseek-key "$DEEPSEEK_API_KEY" ...

# Use MiniMax:
# ai:
#   default_provider: minimax
#   providers:
#     minimax:
#       model: MiniMax-M2.5  # or MiniMax-M2.5-highspeed, MiniMax-M2.1, MiniMax-M2.1-highspeed, MiniMax-M2
#       api_key_env: MINIMAX_API_KEY
#   # Pass at runtime: clanker ask --ai-profile minimax --minimax-key "$MINIMAX_API_KEY" ...

# Multiple AWS environments (dev/stage/prod):
# infra:
#   default_provider: aws
#   default_environment: dev
#   aws:
#     environments:
#       dev:   { profile: your-dev-profile,   region: us-east-1 }
#       stage: { profile: your-stage-profile, region: us-east-1 }
#       prod:  { profile: your-prod-profile,  region: us-east-1 }

# GitHub context for `clanker ask --github ...`:
# github:
#   token: "ghp_..."   # optional for public repos
#   owner: your-org
#   repo: your-repo

# AWS service keywords (used by internal routing). Note: this is under `aws.*`:
# aws:
#   service_keywords:
#     api: [api, gateway]
#     serverless: [lambda, step-functions]

# Postgres (for `clanker postgres ...`):
# postgres:
#   default_connection: dev
#   connections:
#     dev:
#       host: localhost
#       port: 5432
#       database: your_db
#       username: postgres

# Terraform (for `clanker terraform ...` and `clanker ask --terraform ...`):
# terraform:
#   default_workspace: dev
#   workspaces:
#     dev:
#       path: /path/to/infra

# Kubernetes (for `clanker k8s ask ...`):
# kubernetes:
#   kubeconfig: ""           # Path to kubeconfig (default: ~/.kube/config)
#   default_context: ""      # Default kubectl context
#   default_namespace: ""    # Default namespace (empty = all namespaces)
#   clusters:
#     production:
#       type: eks            # eks or existing
#       name: prod-cluster   # EKS cluster name
#       profile: prod-aws    # AWS profile for EKS
#       region: us-east-1
#     staging:
#       type: eks
#       name: staging-cluster
#       profile: dev-aws
#       region: us-west-2
#     local:
#       type: existing       # Use existing kubectl context
#       context: minikube

# Cloudflare (for `clanker cf ask ...` and `clanker ask --cloudflare ...`):
# cloudflare:
#   api_token: ""            # Cloudflare API token (or set CLOUDFLARE_API_TOKEN / CF_API_TOKEN)
#   account_id: ""           # Cloudflare account ID (or set CLOUDFLARE_ACCOUNT_ID / CF_ACCOUNT_ID)
#   default_zone: ""         # Default zone name for DNS operations

# Backend integration (for storing and retrieving credentials across machines):
# backend:
#   # API key for clanker backend authentication (or set CLANKER_BACKEND_API_KEY)
#   api_key: ""
#   # Backend environment: testing, staging, or production (or set CLANKER_BACKEND_ENV)
#   # Default: testing
#   env: "testing"
#   # Custom backend URL, overrides env if set (or set CLANKER_BACKEND_URL)
#   # url: "https://custom-url.example.com"
#
# Use `clanker credentials store aws --profile <profile>` to upload your AWS credentials.
# Then use `clanker ask "..." --api-key <key>` to query using backend credentials.

# General settings:
# timeout: 30
