package cmd

import (
	"encoding/json"
	"fmt"
	"io"
	"os"
	"strings"
	"text/tabwriter"

	"github.com/bgdnvk/clanker/internal/maker"
	"github.com/spf13/cobra"
)

var (
	makerEstimatePlanFile string
	makerEstimateOutput   string
)

var makerCmd = &cobra.Command{
	Use:   "maker",
	Short: "Inspect or operate on plans generated by the maker",
}

var makerEstimateCmd = &cobra.Command{
	Use:   "estimate",
	Short: "Estimate the monthly cost of a maker plan before applying it",
	Long: `Walk a maker plan's commands and produce a static cost estimate
using the on-demand pricing snapshots baked into the CLI.

Reads the plan from --plan <file> or stdin (default).

Recognised commands:
  • aws ec2 run-instances --instance-type X --count N
  • aws rds create-db-instance --db-instance-class X
  • aws lambda create-function (metered, no fixed cost)
  • aws s3 mb / s3api create-bucket (metered)
  • gcloud compute instances create --machine-type=X
  • hcloud server create --type X
  • doctl compute droplet create --size X
  • vercel deploy / vercel pull (metered)

Examples:
  clanker maker estimate < plan.json
  clanker maker estimate --plan plan.json
  clanker maker estimate --plan plan.json -o json`,
	RunE: runMakerEstimate,
}

func init() {
	rootCmd.AddCommand(makerCmd)
	makerCmd.AddCommand(makerEstimateCmd)
	makerEstimateCmd.Flags().StringVar(&makerEstimatePlanFile, "plan", "", "Path to a plan JSON file (default: stdin)")
	makerEstimateCmd.Flags().StringVarP(&makerEstimateOutput, "output", "o", "table", "Output format (table, json)")
}

func runMakerEstimate(cmd *cobra.Command, args []string) error {
	raw, err := readPlanInput(makerEstimatePlanFile)
	if err != nil {
		return err
	}
	plan, err := maker.ParsePlan(string(raw))
	if err != nil {
		return fmt.Errorf("parse plan: %w", err)
	}
	estimate := maker.EstimatePlanCost(plan)

	switch strings.ToLower(makerEstimateOutput) {
	case "json":
		enc := json.NewEncoder(os.Stdout)
		enc.SetIndent("", "  ")
		return enc.Encode(estimate)
	default:
		printPlanCostEstimate(os.Stdout, estimate)
		return nil
	}
}

func readPlanInput(path string) ([]byte, error) {
	if path == "" {
		// Stdin only when something is piped — fail cleanly when stdin
		// is a terminal so the operator gets a usage message instead of
		// a hang.
		if isStdinTerminal() {
			return nil, fmt.Errorf("no plan provided: pass --plan <file> or pipe a plan to stdin")
		}
		return io.ReadAll(os.Stdin)
	}
	return os.ReadFile(path)
}

func isStdinTerminal() bool {
	fi, err := os.Stdin.Stat()
	if err != nil {
		return false
	}
	return (fi.Mode() & os.ModeCharDevice) != 0
}

func printPlanCostEstimate(out io.Writer, est *maker.PlanCostEstimate) {
	if est == nil {
		fmt.Fprintln(out, "No estimate.")
		return
	}
	fmt.Fprintf(out, "Estimated cost: $%.4f/hr  ($%.2f/mo)\n", est.HourlyUSD, est.MonthlyUSD)
	if est.UnknownPriceItems > 0 || est.UnestimatedCommands > 0 {
		fmt.Fprintf(out, "  • %d item(s) without a price match\n", est.UnknownPriceItems)
		fmt.Fprintf(out, "  • %d command(s) not classified (network / IAM / data-only mutations)\n", est.UnestimatedCommands)
	}
	for _, n := range est.Notes {
		fmt.Fprintf(out, "Note: %s\n", n)
	}
	fmt.Fprintln(out)

	if len(est.Items) == 0 {
		fmt.Fprintln(out, "No cost-bearing items in this plan.")
		return
	}

	w := tabwriter.NewWriter(out, 0, 0, 2, ' ', 0)
	fmt.Fprintln(w, "PROVIDER\tRESOURCE\tFAMILY\tCOUNT\tHOURLY\tMONTHLY")
	fmt.Fprintln(w, "--------\t--------\t------\t-----\t------\t-------")
	for _, it := range est.Items {
		hourly := "—"
		monthly := "—"
		if it.PriceKnown {
			hourly = fmt.Sprintf("$%.4f", it.HourlyUSD)
			monthly = fmt.Sprintf("$%.2f", it.MonthlyUSD*float64(it.Count))
		} else if it.Note != "" {
			monthly = it.Note
		}
		fmt.Fprintf(w, "%s\t%s\t%s\t%d\t%s\t%s\n",
			it.Provider, it.Resource, dashIfEmpty(it.Family), it.Count, hourly, monthly,
		)
	}
	w.Flush()
}

func dashIfEmpty(s string) string {
	if s == "" {
		return "—"
	}
	return s
}
